# Generated by Django 2.2.4 on 2019-08-04 19:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20190805_0057'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='heroinfo',
            managers=[
                ('m', django.db.models.manager.Manager()),
            ],
        ),
    ]
